### ISSUE TITLE
Issues with Lockette Plugin

### ISSUE THREAD

**Issue by TH3N3WN00B** [nopjmp/Dionysus#104]
**Describe the bug**
Plugin thows this error:  https://pastebin.com/AnVWf7mv

**To Reproduce**
Set Up a server, install LocketteX, try to place a sign on a chest or door to protect it

**Plugins**
Citizens, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsSpawn, InventoryRollbackPlus, ItemEditor, LocketteX, LuckPerms, nLogin, OpenInv, PlaceholderAPI, ProtocolLib, TAB, Towny, TownyChat, Vault, ViaVersion, WorldEdit, WorldGuard

**Version**
This server is running Dionysus version git-Dionysus-"42ce9ca" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Unknown version, custom build?

**Misc**
Great work my friend, server works amazing with java 19!

**Comment by Kamillaova** [comment]
this plugin doesn't support 1.12.2

**Comment by TH3N3WN00B** [comment]
> this plugin doesn't support 1.12.2

Theres two of them [heres one](https://www.spigotmc.org/resources/lockettex-optimized-simple-chest-protection-plugin.73184/) and [heres the other one](https://www.spigotmc.org/resources/lockettepro-uuid-support-abandoned-restarting.20427/) and neither of them work lmao

**Comment by Kamillaova** [comment]
> https://www.spigotmc.org/resources/20427
with what error does it crash?

**Comment by TH3N3WN00B** [comment]
> > https://www.spigotmc.org/resources/20427
> > with what error does it crash?

Server doesnt crash, plugins simply dont work

**Comment by Kamillaova** [comment]
> Server doesnt crash, plugins simply dont work

test on paper

**Comment by TH3N3WN00B** [comment]
> > Server doesnt crash, plugins simply dont work
> 
> test on paper

I found a previous version and it kinda works

**Comment by Kamillaova** [comment]
> I found a previous version and it kinda works

close issue?

**Comment by 5HT2** [comment]
What's the version difference? Knowing what changed would help narrow down if this is Dionysus's fault or theirs.

**Comment by TH3N3WN00B** [comment]
> What's the version difference? Knowing what changed would help narrow down if this is Dionysus's fault or theirs.

Well, I used [this](https://www.spigotmc.org/resources/lockettex-optimized-simple-chest-protection-plugin.73184/history) plugin, the latest version is 1.7.8 but that didnt worked, so I tested different versions until 1.6.7 worked fine without any issues, there are a lot of changes to list here, feel free to look at the plugin update page
