### ISSUE TITLE
Dionysus can't build

### ISSUE THREAD

**Issue by blauefeuerr** [nopjmp/Dionysus#109]

**Comment by blauefeuerr** [comment]
There is an error in pom.xml

**Comment by Kamillaova** [comment]
> There is an error in pom.xml

no

**Comment by RaymanoPL** [comment]
https://github.com/nopjmp/Dionysus/actions/runs/4053334278/jobs/6973828621
1. Set java jdk 8
2. ./dionysus patch
3.  Set java jdk 17
4. ./dionysus build

**Comment by blauefeuerr** [comment]
com.github.Carleslc.Simple-YAML couldn't be found

**Comment by ghost** [comment]
> com.github.Carleslc.Simple-YAML couldn't be found

now you can
