### ISSUE TITLE
Wrongly backported lag compensated eating.

### ISSUE THREAD

**Issue by interable** [nopjmp/Dionysus#111]
**Describe the bug**
Lag compensated eating is wrongly backported, look at screenshots.

**To Reproduce**
Look at screenshots.

**Plugins**
none

**Version**
latest

**Misc**

Screenshot from Paper 1.16.5 lag compensated patch:
![image](https://user-images.githubusercontent.com/109629887/221410450-9308da89-de94-4ce6-a0b9-4fbe800710be.png)

This part of code is non existing in backported version.
Code should look like this (in EntityLiving.java, line: 2445):
![image](https://user-images.githubusercontent.com/109629887/221410553-1351c3d2-5857-4889-96ae-ff63abe8479a.png)

I do not really know how to work with patches, so if someone else could make pull request it would be great.

**Comment by professorparabellum** [comment]
Not sure if this is related but i noticed that often times eating something happens instantaneously when you right click.
