### ISSUE TITLE
Reset-players-airTicks-on-respawn 

### ISSUE THREAD

**Issue by ghost** [nopjmp/Dionysus#115]
**Describe the bug**
When /kil and spawn water and /kill again spawn water you killing without bubbles
You have this patch but this patch not working. 
Your patch: https://github.com/nopjmp/Dionysus/blob/dev/patches/server/0067-Reset-players-airTicks-on-respawn.patch
Reaper ( Tested it working ) patch: https://github.com/ruViolence/Reaper/blob/ver/1.12.2/patches/server/0123-fix-reset-players-airTicks-on-respawn.patch

**Comment by nopjmp** [comment]
Is this expected behavior the same in later versions of Minecraft?

**Comment by ghost** [comment]
> Is this expected behavior the same in later versions of Minecraft?

i dont know

**Comment by ghost** [comment]
> > Is this expected behavior the same in later versions of Minecraft?
> 
> i dont know

in new versions you can't spawn in water with gamerule
