### ISSUE TITLE
Compatibility with premium plugin — Plugin Hide Pro

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [nopjmp/Dionysus#135]
**Describe the bug**
When using this plugin, with its dependency plugins (PacketEventsAPI & LuckPerms), the plugin does not work for tabcompleting.
Plugin in question: [Plugin Hide Pro](https://www.spigotmc.org/resources/%E2%9C%94%EF%B8%8F-plugin-hide-pro-decide-which-commands-are-executable-and-visible-spigot-bungee-velocity-%E2%9C%94%EF%B8%8F.77112/)

**To Reproduce**
1. Start Dionysus server
2. Put in `Pl-Hide-Pro`, `packetevents` & `LuckPerms` plugins
3. Configure them or use out of box and try to tabcomplete something configured

**Plugins**
Pl-Hide-Pro, PacketEventsAPI, LuckPerms

**Version**
[18:55:55 INFO]: This server is running Dionysus version git-Dionysus-"8d3095e" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:55:55 INFO]: Previous version: git-Paper-1620 (MC: 1.12.2)

**Misc**
/

**Comment by MotikaCraft-TheJoshua** [comment]
Anyone? @nopjmp

**Comment by TH3N3WN00B** [comment]
My guy, please provide less information next time, this is too much...

Sarcasm aside, send logs bro... https://mclo.gs/

**Comment by MotikaCraft-TheJoshua** [comment]
> My guy, please provide less information next time, this is too much...
> 
> Sarcasm aside, send logs bro... https://mclo.gs/

My deep apologizes
By default (idk why?), in `spigot.yml`, option `tab-complete` is set to `-1` (disabled) instead of `0`...

Everything works, sorry for confusion...
