### ISSUE TITLE
Question: Async Chunks and no tick view distance

### ISSUE THREAD

**Issue by Imptovskii** [nopjmp/Dionysus#19]
I have such a question. Is there a possibility to backport Async Chunks and no tick view distance, from new versions of PaperMC? I personally would like to get this in version 1.12.2. Or is it impossible to implement it, due to the limitations of version 1.12.2?

**Comment by nopjmp** [comment]
Async chunks requires newer Minecraft internals which I don't have time to rewrite nor motivation to.

If someone else wants to do that have at it, but unfortunately it would require basics backporting 1.13 code and you are better off running ViaVersion on a newer version of Minecraft.

**Comment by Imptovskii** [comment]
Thanks a lot for the answer, I thought about it that way.
