### ISSUE TITLE
[FEATURE] Different World Compression

### ISSUE THREAD

**Issue by dG9hc3Q** [nopjmp/Dionysus#20]
**Describe the solution you'd like**
Use [zstd](https://github.com/facebook/zstd) for world compression which is not only faster, but also has a much bigger compression ratio. 

Instead of 24 year old library 'zlib' (which mc uses by default)

[Here](https://github.com/facebook/zstd/blob/dev/doc/images/CSpeed2.png) you can see a comparison between zlib and zstd.

**Comment by AlexProgrammerDE** [comment]
Has been implemented in https://github.com/nopjmp/Dionysus/commit/2573a0de1577b95550901059cd158bd30c3532b0#diff-d7e5f0410d1ebd0e3964fb98cb21aa6e7310aa2cf1e4d8c9e8a691c393b44e20
