### ISSUE TITLE
Change of world time

### ISSUE THREAD

**Issue by GodOfBurrito** [nopjmp/Dionysus#27]
Hello, i had other server core for 1.12.2, when i deletet old core and instaled this new, I noticed an problem, when i go frome one gamemode to other (for example from gamemode 3 to gamemode 1), my time change, from night to day, maybe it can fix in configs of core?

**Comment by GodOfBurrito** [comment]
Other example, when an player leave from server, time change too

**Comment by dG9hc3Q** [comment]
this is almost definitely caused by one of your plugins, remove them all and try again

**Comment by GodOfBurrito** [comment]
hmmmm, yes you are right, that plugins

**Comment by GodOfBurrito** [comment]
I checked the plugins and noticed that EssentialsX cause this phenomenon

**Comment by AlexProgrammerDE** [comment]
Closing as it is resolved
