### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by kev626** [nopjmp/Dionysus#29]
Hello,

Recently you pulled patches from my fork, Pufferfish. You are attempting to release these patches under the MIT license, and you have not properly provided attribution. Please see how Purpur has done this, and include a similar/identical note in the header of every Pufferfish patch: https://github.com/PurpurMC/Purpur/blob/ver/1.19/patches/server/0001-Pufferfish-Server-Changes.patch#L6-L20

Thank you

**Comment by nopjmp** [comment]
We are looking into fixing this properly as a high priority issue. I'm just busy with my IRL job right now. I'll see about getting original patch creator to work on fixing it.

**Comment by AlexProgrammerDE** [comment]
Has been fixed with https://github.com/nopjmp/Dionysus/commit/41ff663a550107807d28fdeeb417b483cede5b04
