### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by EliasDavid256** [nopjmp/Dionysus#34]
**Describe the bug**
Since I updated to the latest version of the fork, I have an entity problem that kills my server and it happens with some frequency (every 3 - 12 hours).

**To Reproduce**
I haven't found a way to reproduce it as such. I only have the crash log.

**Version**
1.12.2 - Dionysus v0.1.15

**Misc**
https://pastebin.com/C6txD9LJ

**Comment by dG9hc3Q** [comment]
Try with Java 17 and test without your plugins and add them back 1 by 1

**Comment by AlexProgrammerDE** [comment]
Closed due to inactivity.
