### ISSUE TITLE
Performance & Bugs Question

### ISSUE THREAD

**Issue by dani31c** [nopjmp/Dionysus#37]
Is this software buggy?
Difference towards paper?
Can i move from paper to Dionysus?

**Comment by dani31c** [comment]
I also had plugins, and idk if they'd work

**Comment by xKumorio** [comment]
From personal observation, I can say that it is better than any other. All plugins that support java 17 will work

**Comment by dani31c** [comment]
Well, plugins would work on Java 8? As most of them wont even work past Java 11

**Comment by dani31c** [comment]
It includes protocolsupport, viaversion, etc.

**Comment by xKumorio** [comment]
Try putting this on and see if it's okay

**Comment by AlexProgrammerDE** [comment]
We have been using ViaVersion perfectly fine. Java 17 allows loading plugins made for Java 1.8, 11, 16 and more.
What Softik was referring to is that some plugins use code that only works on Java 1.8, but those cases are rare.

**Comment by dani31c** [comment]
Sure, I will try in 1 hour and ill tell you if it works fine, as i want to move from paper to this one, since its for a unic-server network

**Comment by dani31c** [comment]
I also tried it without plugins and help very well the ram and cpu usage,also that the tps was above expected after mild mob spam and tnts (19.90), paper would've died a bit

**Comment by dani31c** [comment]
All seems to work nominal! TY
