### ISSUE TITLE
Wrong patch autor

### ISSUE THREAD

**Issue by ghost** [nopjmp/Dionysus#50]
https://github.com/nopjmp/Dionysus/blob/dev/patches/server/0132-Cache-chunk-coordinations.patch
This patch was made by me, please change the author to me or drop this patch
From: Lew <skycubesv@gmail.com>

**Comment by 5HT2** [comment]
Source?

**Comment by ghost** [comment]
> Source?

Original commit
https://github.com/CobbleSword/NachoSpigot/commit/76966334a9e509f45a3272d32dc8d85de5d41957

**Comment by AlexProgrammerDE** [comment]
Resolved with https://github.com/nopjmp/Dionysus/commit/939fb4af8ec81a581f3fd2a973ca9ae091030c4c
