### ISSUE TITLE
[FEATURE] Crystal Death Event

### ISSUE THREAD

**Issue by dG9hc3Q** [nopjmp/Dionysus#93]
**Describe the solution you'd like**
End crystal death events (e.g end crystal placer)

**Comment by comendantmc** [comment]
There is a plugin for that, it's called DMEnderCrystal (DMP extention).

**Comment by dG9hc3Q** [comment]
The plugin is a) a plugin b) throws exceptions

It would be much cleaner if Dionysus made end crystals track their placer so then you could get the killer with entity damage event

**Comment by AlexProgrammerDE** [comment]
You can easily do that with just the spigot API though. Such a event would be kind of unnecessary and unwanted for most users.
